name: 'Deploy to Sandbox'

on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]

  workflow_dispatch:

jobs:
  create:
    name: 'Create Release Branch'
    runs-on: ubuntu-latest

    steps:
      - name: 'Create Branch'
        uses: peterjgrainger/action-create-branch@v2.4.0
        env:
          GITHUB_TOKEN: ${{ secrets.VERAN }}
        with:
          branch: sandbox
          sha: ${{ github.sha }}

  tests:
    runs-on: ubuntu-latest
    needs: [create]

    strategy:
      fail-fast: true
      matrix:
        php: [8.1, 8.2]

    name: PHP ${{ matrix.php }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: sandbox

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite
          coverage: none

      - name: Install Composer dependencies
        run: composer install --prefer-dist --no-interaction --no-progress

      - name: Copy environment file
        run: cp .env.example .env

      - name: Generate app key
        run: php lotus key:generate

      - name: Setup Node
        uses: actions/setup-node@v3.6.0
        with:
          node-version: 'lts/*'

      - name: Install Dependencies
        run: npm install

      - name: Build assets
        run: npm run prod

      - name: Execute tests
        run: php lotus test

  build:
    name: 'Build Sandbox'
    needs: [tests, create]
    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout Release'
        uses: actions/checkout@v3
        with:
          ref: sandbox

      - name: Generate .env File
        run: cp .env.example .env

      - name: Install PHP
        uses: shivammathur/setup-php@master
        with:
          php-version: '8.1'

      - name: Install Composer Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

      - name: Install Node
        uses: actions/setup-node@v3.6.0
        with:
          node-version: 'lts/*'

      - run: npm install
      - run: npm run prod --force

      - name: Commit Assets to Sandbox
        uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actor
          message: 'chore(deploy): deploy develop repo to sandbox'
          add: '-f public/'
          push: '-f origin sandbox'

  deploy:
    name: Deploy to Laravel Forge
    needs: [build, tests, create]
    runs-on: ubuntu-latest

    steps:
      - name: Deploy Production Code
        uses: jbrooksuk/laravel-forge-action@v1.0.4
        with:
          trigger_url: ${{ secrets.SANDBOX_TRIGGER }}

  remove:
    name: Remove Latest Branch
    needs: [deploy, build, tests, create]
    runs-on: ubuntu-latest

    steps:
      - name: Delete Latest
        uses: dawidd6/action-delete-branch@v3
        with:
          github_token: ${{ secrets.VERAN }}
          branches: sandbox
