name: Test + Release

on:
  push:
    branches:
      - '1.x'

  workflow_dispatch:

jobs:
  tests:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true
      matrix:
        php: [8.1, 8.2]

    name: PHP ${{ matrix.php }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: '1.x'

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite
          coverage: none

      - name: Install Composer dependencies
        run: composer install --prefer-dist --no-interaction --no-progress

      - name: Copy environment file
        run: cp .env.example .env

      - name: Generate app key
        run: php lotus key:generate

      - name: Setup Node
        uses: actions/setup-node@v3.6.0
        with:
          node-version: 'lts/*'

      - name: Install Dependencies
        run: npm install

      - name: Build assets
        run: npm run prod

      - name: Execute tests
        run: php lotus test

  release:
    name: Release 1.x
    needs: [tests]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 1.x
        uses: actions/checkout@v3
        with:
          ref: main
          fetch-depth: 0
          persist-credentials: false

      - name: Setup Node
        uses: actions/setup-node@v3.6.0
        with:
          node-version: 'lts/*'

      - name: Install Dependencies
        run: npm install

      - name: Run Semantic Release
        env:
          GH_TOKEN: ${{ secrets.SM_RELEASE}}
          GITHUB_TOKEN: ${{ secrets.VERAN }}
        run: npx semantic-release
